# Generated by Django 4.2.6 on 2023-10-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penjual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, unique=True)),
                ('umur', models.IntegerField()),
                ('perempuan', models.BooleanField(default=False)),
            ],
        ),
    ]
