# Generated by Django 4.2.6 on 2023-10-14 04:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_penjual_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('alamat', models.TextField()),
                ('foto', models.ImageField(upload_to='foto_toko')),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
